lab4/flask_app_db/app/models/__init__.py
# импортируем модели
from .user import User
from .order import Order

lab4/flask_app_db/app/models/order.py
# импортируем SQLAlchemy
from app import db


# определение модели Order
class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    product_name = db.Column(db.String(50), nullable=False)
    price = db.Column(db.Float, nullable=False)
    quantity = db.Column(db.Integer, nullable=False)
    order_date = db.Column(db.Date, nullable=False)

    user = db.relationship('User', backref=db.backref('orders', lazy=True))

    # возвращает строковое представление объекта
    def __repr__(self):
        return f'<Order {self.product_name}>'

lab4/flask_app_db/app/models/user.py
# импортируем SQLAlchemy
from app import db


# определение модели User
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(50), nullable=False, unique=True)
    age = db.Column(db.Integer, nullable=False)
    country = db.Column(db.String(50), nullable=False)
    balance = db.Column(db.Float, nullable=False)

    # возвращает строковое представление объекта
    def __repr__(self):
        return f'<User {self.name}>'

lab4/flask_app_db/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)

    # загружаем конфигурацию
    app.config.from_object('app.config.Config')

    # инициализируем расширения
    db.init_app(app)

    # регистрируем маршруты
    from .routes import bp as main_routes
    app.register_blueprint(main_routes)

    from .routes import user_routes
    app.register_blueprint(user_routes.bp)

    from .routes import order_routes
    app.register_blueprint(order_routes.bp)

    return app

lab4/flask_app_db/app/routes/__init__.py
from flask import Blueprint, render_template

bp = Blueprint('main_routes', __name__)


@bp.route('/')
def index():
    return render_template('index.html')

lab4/flask_app_db/app/routes/order_routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models import Order
from app import db

bp = Blueprint('order_routes', __name__)


@bp.route('/orders', methods=['GET'])
def get_orders():
    orders = Order.query.all()
    return render_template('order.html', orders=orders)


@bp.route('/orders', methods=['POST'])
def add_order():
    user_id = request.form['user_id']
    product_name = request.form['product_name']
    price = request.form['price']
    quantity = request.form['quantity']
    order_date = request.form['order_date']

    new_order = Order(user_id=user_id, product_name=product_name, price=price, quantity=quantity, order_date=order_date)
    db.session.add(new_order)
    db.session.commit()

    return redirect(url_for('order_routes.get_orders'))

lab4/flask_app_db/app/routes/user_routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models import User
from app import db

bp = Blueprint('user_routes', __name__)


@bp.route('/users', methods=['GET'])
def get_users():
    users = User.query.all()
    return render_template('user.html', users=users)


@bp.route('/users', methods=['POST'])
def add_user():
    name = request.form['name']
    email = request.form['email']
    age = request.form['age']
    country = request.form['country']
    balance = request.form['balance']

    new_user = User(name=name, email=email, age=age, country=country, balance=balance)
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('user_routes.get_users'))

lab4/flask_app_db/app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

lab4/flask_app_db/app/templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная страница</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <h1>Добро пожаловать!</h1>
    <div class="buttons">
       <a href="{{ url_for('user_routes.get_users') }}" class="button">Пользователи</a>
        <a href="{{ url_for('order_routes.get_orders') }}" class="button">Заказы</a>
    </div>
</body>
</html>

lab4/flask_app_db/app/templates/order.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Заказы</h1>

    <a href="{{ url_for('main_routes.index') }}">На главную</a>

    <form action="{{ url_for('order_routes.add_order') }}" method="POST">
        <label for="user_id">ID пользователя:</label>
        <input type="number" id="user_id" name="user_id" required>
        <label for="product_name">Название товара:</label>
        <input type="text" id="product_name" name="product_name" required>
        <label for="price">Цена:</label>
        <input type="number" id="price" name="price" step="0.01" required>
        <label for="quantity">Количество:</label>
        <input type="number" id="quantity" name="quantity" required>
        <label for="order_date">Дата заказа:</label>
        <input type="date" id="order_date" name="order_date" required>
        <button type="submit">Добавить заказ</button>
    </form>

    <table>
        <tr>
            <th>ID</th>
            <th>Пользователь</th>
            <th>Товар</th>
            <th>Цена</th>
            <th>Количество</th>
            <th>Дата заказа</th>
        </tr>
        {% for order in orders %}
        <tr>
            <td>{{ order.id }}</td>
            <td>{{ order.user.name }}</td>
            <td>{{ order.product_name }}</td>
             <td>{{ order.price }}</td>
            <td>{{ order.quantity }}</td>
            <td>{{ order.order_date }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

lab4/flask_app_db/app/templates/user.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h1>Пользователи</h1>
    <a href="{{ url_for('main_routes.index') }}">На главную</a>
    <form action="{{ url_for('user_routes.add_user') }}" method="POST">
        <label for="name">Имя:</label>
        <input type="text" id="name" name="name" required>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        <label for="age">Возраст:</label>
        <input type="number" id="age" name="age" required>
        <label for="country">Страна:</label>
        <input type="text" id="country" name="country" required>
        <label for="balance">Баланс:</label>
        <input type="number" id="balance" name="balance" required>
        <button type="submit">Добавить пользователя</button>
    </form>
    <table>
        <tr>
            <th>ID</th>
            <th>Имя</th>
            <th>Email</th>
            <th>Возраст</th>
            <th>Страна</th>
            <th>Баланс</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.age }}</td>
            <td>{{ user.country }}</td>
            <td>{{ user.balance }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}